(function(g){var window=this;var Pxa=function(a,b){return g.Rb(a,b)},I6=function(a){g.zm(a,"zx",g.wb());
return a},J6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Cm(a.g,b,c)},Qxa=function(a,b){var c=[];
g.lk(b,function(a){try{var b=g.CC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.BC(b)&&c.push(a):c.push(a)},a);
return c},Rxa=function(a,b){var c=Qxa(a,b);
(0,g.C)(c,function(a){g.CC.prototype.remove.call(this,a)},a)},Sxa=function(){var a=g.$F;
Rxa(a,a.g.be(!0))},Txa=function(a,b,c,d){var e=new g.qm(null,void 0);
a&&g.rm(e,a);b&&g.sm(e,b);c&&g.tm(e,c);d&&g.um(e,d);return e},Uxa=function(a){g.jF[a]&&(a=g.jF[a],(0,g.C)(a,function(a){g.hF[a]&&delete g.hF[a]}),a.length=0)},Vxa=function(a){var b=g.gF();
if(b)if(b.clear(a),a)Uxa(a);else for(var c in g.jF)Uxa(c)},K6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.km;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Wxa(this,a.capabilities||""),Xxa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Wxa=function(a,b){a.capabilities.clear();
(0,g.Hd)(b.split(","),g.Fa(Pxa,Yxa)).forEach(function(b){a.capabilities.add(b)})},Xxa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},L6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},M6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Zxa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},$xa=function(a){return new L6(a)},aya=function(a){return g.za(a)?(0,g.I)(a,$xa):[]},N6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},O6=function(a){return g.za(a)?"["+(0,g.I)(a,N6).join(",")+"]":"null"},P6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},bya=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Q6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},R6=function(a,b){return g.La(a,function(a){return M6(a,b)})},S6=function(){var a=g.cG("yt-remote-connected-devices")||[];
g.fb(a);return a},cya=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},dya=function(a){g.bG("yt-remote-connected-devices",a,86400)},U6=function(){if(T6)return T6;
var a=g.cG("yt-remote-device-id");a||(a=P6(),g.bG("yt-remote-device-id",a,31536E3));for(var b=S6(),c=1,d=a;g.D(b,d);)c++,d=a+"#"+c;return T6=d},V6=function(){var a=S6(),b=U6();
g.D(a,b);g.hG()&&g.ib(a,b);a=cya(a);if(g.Pa(a))try{g.fG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.gG("remote_sid",a.join(","),-1)}catch(c){}},eya=function(){return g.cG("yt-remote-session-browser-channel")},fya=function(){return g.cG("yt-remote-local-screens")||[]},gya=function(){g.bG("yt-remote-lounge-token-expiration",!0,86400)},hya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(fya(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Zl)(c,function(a){return!g.D(b,a)})&&gya();
g.bG("yt-remote-local-screens",a,31536E3)},iya=function(a,b){g.bG("yt-remote-session-browser-channel",a);
g.bG("yt-remote-session-screen-id",b);var c=S6(),d=U6();g.D(c,d)||c.push(d);dya(c);V6()},W6=function(a){a||(g.dG("yt-remote-session-screen-id"),g.dG("yt-remote-session-video-id"));
V6();a=S6();g.Ta(a,U6());dya(a)},jya=function(){if(!X6){var a=g.IC();
a&&(X6=new g.wC(a))}return X6?!!X6.get("yt-remote-use-staging-server"):!1},kya=function(){var a=window.document.createElement("a");
g.Tc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},lya=function(a,b){var c=g.zd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Uc(c,g.Yd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},mya=function(){var a=kya(),b=window.document.getElementById(a),c=b&&g.vE(b,"loaded");
c||b&&!c||(b=lya(a,function(){g.vE(b,"loaded")||(g.uE(b,"loaded","true"),g.nF(a),g.qD(g.Fa(Vxa,a),0))}))},Y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},nya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Z6=function(a){a.length?oya(a.shift(),function(){Z6(a)}):$6()},pya=function(a){return"chrome-extension://"+a+a7},oya=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},b7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},$6=function(){var a=nya();
a&&a(!1,"No cast extension found")},c7=function(){if(qya){var a=2,b=nya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;oya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",$6,c)}},rya=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(c7(),a({command:"cast.sender.init"}))},sya=function(){c7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+a7,"//www.gstatic.com/eureka/clank"+a7])},d7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.qc=b;this.B=(0,g.z)(this.wH,this);this.g=!1;this.l=0;this.o=this.ua=null;this.A=[]},e7=function(){},f7=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Gm(this);this.l=new g.mg;this.l.setInterval(250)},uya=function(a,b,c){a.mj=1;
a.jh=I6(b.clone());a.Fi=c;a.C=!0;tya(a,null)},g7=function(a,b,c,d,e){a.mj=1;
a.jh=I6(b.clone());a.Fi=null;a.C=c;e&&(a.UB=!1);tya(a,d)},tya=function(a,b){a.Pj=(0,g.H)();
h7(a);a.Ch=a.jh.clone();J6(a.Ch,"t",a.D);a.Ol=0;a.Lc=a.g.pq(a.g.Il()?b:null);0<a.Uq&&(a.Ho=new g.Nk((0,g.z)(a.fD,a,a.Lc),a.Uq));a.A.R(a.Lc,"readystatechange",a.sS);var c=a.fi?g.Yb(a.fi):{};a.Fi?(a.qp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Lc.send(a.Ch,a.qp,a.Fi,c)):(a.qp="GET",a.UB&&!g.ud&&(c.Connection="close"),a.Lc.send(a.Ch,a.qp,null,c));a.g.rf(1)},xya=function(a,b,c){for(var d=!0;!a.Qh&&a.Ol<c.length;){var e=vya(a,c);
if(e==i7){4==b&&(a.kh=4,j7(15),d=!1);break}else if(e==wya){a.kh=4;j7(16);d=!1;break}else k7(a,e)}4==b&&0==c.length&&(a.kh=1,j7(17),d=!1);a.vf=a.vf&&d;d||(l7(a),m7(a))},vya=function(a,b){var c=a.Ol,d=b.indexOf("\n",c);
if(-1==d)return i7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return wya;d+=1;if(d+c>b.length)return i7;var e=b.substr(d,c);a.Ol=d+c;return e},zya=function(a,b){a.Pj=(0,g.H)();
h7(a);var c=b?window.location.hostname:"";a.Ch=a.jh.clone();g.zm(a.Ch,"DOMAIN",c);g.zm(a.Ch,"t",a.D);try{a.wf=new window.ActiveXObject("htmlfile")}catch(n){l7(a);a.kh=7;j7(22);m7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in n7)k=n7[l];else if(l in yya)k=n7[l]=yya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=n7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Vc(g.sc("b/12014412"),d);a.wf.open();a.wf.write(g.Nc(c));a.wf.close();a.wf.parentWindow.m=(0,g.z)(a.wR,a);a.wf.parentWindow.d=(0,g.z)(a.lB,a,!0);a.wf.parentWindow.rpcClose=(0,g.z)(a.lB,a,!1);c=a.wf.createElement("DIV");a.wf.parentWindow.document.body.appendChild(c);d=g.Ec(a.Ch.toString());d=g.pb(g.Bc(d));d=g.Vc(g.sc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Nc(d);
a.g.rf(1)},h7=function(a){a.Eu=(0,g.H)()+a.B;
Aya(a,a.B)},Aya=function(a,b){if(null!=a.jk)throw Error("WatchDog timer not null");
a.jk=o7((0,g.z)(a.OR,a),b)},p7=function(a){a.jk&&(g.w.clearTimeout(a.jk),a.jk=null)},m7=function(a){a.g.xx()||a.Qh||a.g.xo(a)},l7=function(a){p7(a);
g.Ue(a.Ho);a.Ho=null;a.l.stop();g.Mm(a.A);if(a.Lc){var b=a.Lc;a.Lc=null;b.abort();b.dispose()}a.wf&&(a.wf=null)},k7=function(a,b){try{a.g.eB(a,b),a.g.rf(4)}catch(c){}},Cya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Bya(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Cya(a,b,c,d,f)},f)})}},Bya=function(a,b,c){var d=new window.Image;
d.onload=function(){try{q7(d),c(!0)}catch(e){}};
d.onerror=function(){try{q7(d),c(!1)}catch(e){}};
d.onabort=function(){try{q7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},q7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Dya=function(a){this.g=a;
this.l=new e7},Eya=function(a){var b=r7(a.g,a.pk,"/mail/images/cleardot.gif");
I6(b);Cya(b.toString(),5E3,(0,g.z)(a.IG,a),3,2E3);a.rf(1)},t7=function(a){var b=a.g.H;
if(null!=b)j7(5),b?(j7(11),s7(a.g,a,!1)):(j7(12),s7(a.g,a,!0));else if(a.re=new f7(a,void 0,void 0,void 0),a.re.fi=a.Rq,b=a.g,b=r7(b,b.Il()?a.Ok:null,a.Tq),j7(5),!g.sd||g.oc(10))J6(b,"TYPE","xmlhttp"),g7(a.re,b,!1,a.Ok,!1);else{J6(b,"TYPE","html");var c=a.re;a=!!a.Ok;c.mj=3;c.jh=I6(b.clone());zya(c,a)}},u7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new e7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},Fya=function(a,b){this.g=a;
this.map=b;this.context=null},Gya=function(a){g.We.call(this,"statevent",a)},Hya=function(a,b){g.We.call(this,"timingevent",a);
this.size=b},Iya=function(a){g.We.call(this,"serverreachability",a)},Lya=function(a){Jya(a);
if(3==a.g){var b=a.xl++,c=a.tn.clone();g.zm(c,"SID",a.o);g.zm(c,"RID",b);g.zm(c,"TYPE","terminate");v7(a,c);b=new f7(a,a.o,b,void 0);b.mj=2;b.jh=I6(c.clone());(new window.Image).src=b.jh;b.Pj=(0,g.H)();h7(b)}Kya(a)},Mya=function(a){a.dH(1,0);
a.tn=r7(a,null,a.Qq);w7(a)},Jya=function(a){a.Yg&&(a.Yg.abort(),a.Yg=null);
a.kc&&(a.kc.cancel(),a.kc=null);a.qg&&(g.w.clearTimeout(a.qg),a.qg=null);x7(a);a.Pd&&(a.Pd.cancel(),a.Pd=null);a.ah&&(g.w.clearTimeout(a.ah),a.ah=null)},Nya=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new Fya(a.tN++,b));2!=a.g&&3!=a.g||w7(a)},w7=function(a){a.Pd||a.ah||(a.ah=o7((0,g.z)(a.jB,a),0),a.ej=0)},Pya=function(a,b){if(1==a.g){if(!b){a.xl=Math.floor(1E5*Math.random());
var c=a.xl++,d=new f7(a,"",c,void 0);d.fi=null;var e=y7(a),f=a.tn.clone();g.zm(f,"RID",c);g.zm(f,"CVER","1");v7(a,f);uya(d,f,e);a.Pd=d;a.g=2}}else 3==a.g&&(b?Oya(a,b):0==a.l.length||a.Pd||Oya(a))},Oya=function(a,b){if(b)if(6<a.Sh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.xl-1;var d=y7(a)}else c=b.F,d=b.Fi;else c=a.xl++,d=y7(a);var e=a.tn.clone();g.zm(e,"SID",a.o);g.zm(e,"RID",c);g.zm(e,"AID",a.yj);v7(a,e);c=new f7(a,a.o,c,a.ej+1);c.fi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Pd=c;uya(c,e,d)},v7=function(a,b){if(a.kd){var c=a.kd.Xw();
c&&g.Ib(c,function(a,c){g.zm(b,c,a)})}},y7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Sh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Sh?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},Qya=function(a){a.kc||a.qg||(a.D=1,a.qg=o7((0,g.z)(a.iB,a),0),a.Vi=0)},z7=function(a){if(a.kc||a.qg||3<=a.Vi)return!1;
a.D++;a.qg=o7((0,g.z)(a.iB,a),Rya(a,a.Vi));a.Vi++;return!0},s7=function(a,b,c){a.pp=c;
a.gf=b.yg;a.C||Mya(a)},x7=function(a){null!=a.Uh&&(g.w.clearTimeout(a.Uh),a.Uh=null)},Rya=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},A7=function(a,b){if(2==b||9==b){var c=null;
a.kd&&(c=null);var d=(0,g.z)(a.nT,a);c||(c=new g.qm("//www.google.com/images/cleardot.gif"),I6(c));Bya(c.toString(),1E4,d)}else j7(2);Sya(a,b)},Sya=function(a,b){a.g=0;
a.kd&&a.kd.Xv(b);Kya(a);Jya(a)},Kya=function(a){a.g=0;
a.gf=-1;if(a.kd)if(0==a.A.length&&0==a.l.length)a.kd.eq();else{g.Wa(a.A);var b=g.Wa(a.l);a.A.length=0;a.l.length=0;a.kd.eq(b)}},r7=function(a,b,c){var d=g.Am(c);
if(""!=d.l)b&&g.sm(d,b+"."+d.l),g.tm(d,d.B);else{var e=window.location;d=Txa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Bk&&g.Ib(a.Bk,function(a,b){g.zm(d,b,a)});
g.zm(d,"VER",a.Sh);v7(a,d);return d},o7=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j7=function(a){B7.dispatchEvent(new Gya(B7,a))},Tya=function(){},Uya=function(a,b){this.action=a;
this.params=b||{}},D7=function(a,b){g.M.call(this);
this.g=new g.Pt(this.o,0,this);g.N(this,this.g);this.l=this.qc=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;C7(this)},C7=function(a){a.g.stop();
a.qc=5E3+2E4*Math.random()},E7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.vC;this.l=new D7(this.UT,this);this.g=this.Za=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},Vya=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.pp,sessionId:a.g.o,arrayId:a.g.yj}},Wya=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&Pya(a.g),Lya(a.g));a.F=0},F7=function(a){return!!a.g&&3==a.g.g},Xya=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},G7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Cg(a)||"";b&&(this.port=":"+b);this.domain=g.Bg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},H7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Lg(c+b,{})},I7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),nd:g.Fa(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.GD(b,a)},aza=function(){var a=Yya;
Zya();J7.push(a);$ya(J7)},K7=function(a,b){Zya();
var c=J7,d=bza(a,String(b));g.Pa(c)?cza(d):($ya(c),(0,g.C)(c,function(a){a(d)}))},Zya=function(){J7||(J7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",J7,void 0))},cza=function(a){var b=(L7+1)%50;
L7=b;M7[b]=a;N7||(N7=49==b)},$ya=function(a){var b=M7;
if(b[0]){var c=L7,d=N7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
M7=Array(50);L7=-1;N7=!1}},bza=function(a,b){var c=((0,g.H)()-dza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O7=function(a){g.$E.call(this);
this.D=a;this.g=[]},eza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},fza=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Hd)(a.g,function(a){return!!Q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=eza(a,b[d])||c;return c},gza=function(a,b){var c=a.g.length;
a.g=(0,g.Hd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},P7=function(a,b,c,d){g.$E.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.ua=window.NaN},R7=function(a){O7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;Q7(this);this.info("Initializing with "+O6(this.g))},hza=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=H7(a.o,"/pairing/get_lounge_token_batch");
I7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.IH,a),(0,g.z)(a.HH,a))}},Q7=function(a){var b=aya(fya());
b=(0,g.Hd)(b,function(a){return!a.uuid});
return fza(a,b)},S7=function(a,b){hya((0,g.I)(a.g,Zxa));
b&&gya()},U7=function(a,b){g.$E.call(this);
this.C=b;var c=g.cG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.D(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;T7("Initialized with "+g.tg(this.g))},iza=function(a,b,c){var d=H7(a.B,"/pairing/get_screen_availability");
I7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},V7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.g))var c=!1;
else{c=g.Ob(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T7("Updated online screens: "+g.tg(a.g)),a.g=b,a.P("screenChange"));jza(a)},W7=function(a){(0,window.isNaN)(a.o)||g.sD(a.o);
a.o=g.qD((0,g.z)(a.Ot,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},T7=function(a){K7("OnlineScreenService",a)},kza=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.Zb("Requesting availability of screen w/o lounge token.")});
return b},jza=function(a){a=g.Ob(g.Jb(a.g,function(a){return a}));
g.fb(a);a.length?g.bG("yt-remote-online-screen-ids",a.join(","),60):g.dG("yt-remote-online-screen-ids")},X7=function(a){O7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};lza(this)},nza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.je();if(k=(c?R6(k,c):null)||R6(k,b)){k.uuid=b;var l=Y7(a,k);iza(a.l,l,function(a){e(a?l:null)})}else c?mza(a,c,(0,g.z)(function(a){var f=Y7(this,new L6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));iza(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},oza=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},mza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.GD(H7(a.C,"/pairing/get_lounge_token_batch"),e)},pza=function(a){a.g=a.o.je();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+O6(a.g))},lza=function(a){Z7(a);
a.o=new R7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.YH,a));pza(a);a.A=aya(g.cG("yt-remote-automatic-screen-cache")||[]);Z7(a);a.info("Initializing automatic screens: "+O6(a.A));a.l=new U7(a.C,(0,g.z)(a.je,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},Y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=R6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.bG("yt-remote-automatic-screen-cache",(0,g.I)(a.A,Zxa)));Z7(a);a.B[b.uuid]=b.id;g.bG("yt-remote-device-id-map",a.B,31536E3);return b},Z7=function(a){a.B=g.cG("yt-remote-device-id-map")||{}},$7=function(a,b,c){g.$E.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},a8=function(a,b){K7(a.M,b)},b8=function(a,b){$7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.cU,this);this.B=(0,g.z)(this.YR,this);this.A=g.qD((0,g.z)(function(){qza(this,null)},this),12E4)},rza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.tg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){a8(this,"Failed to send message: getMdxSessionStatus.")},a)):a8(a,"Sending yt message without session: "+g.tg(b))},qza=function(a,b){g.sD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.yo,a),d=(0,g.z)(a.pe,a);a.mx(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},c8=function(a,b,c){$7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.fU,this);this.g=g.y},sza=function(a){a.g=a.H.lD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.yo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.pe(a)},a))},tza=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}jya()&&(b.env_useStageMdx=1);return g.Jg(b)},d8=function(a,b){$7.call(this,a,b,"ManualSession");
this.g=g.qD((0,g.z)(this.zj,this,null),150)},e8=function(a,b,c,d){g.$E.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.EQ,this)},uza=function(a,b){return b?g.La(a.o,function(a){return M6(b,a.label)},a):null},f8=function(a){K7("Controller",a)},Yya=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},g8=function(a){return a.B||!!a.o.length||!!a.g},h8=function(a,b,c){b!=a.g&&(g.Ue(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.gB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.zj(null)):a.P("yt-remote-cast2-session-change",null))},vza=function(a){var b=a.l.kD(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&M6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=uza(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Bza=function(a,b,c,d,e,f,k){wza()?xza(b,e,f,k)&&(j8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?yza(a,c):(window.__onGCastApiAvailable=function(b,d){b?yza(a,c):(k8("Failed to load cast API: "+d),l8(!1),j8(!1),g.dG("yt-remote-cast-available"),g.dG("yt-remote-cast-receiver"),zza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):mya():b7("CriOS")?rya():b7("Android")&&b7("Chrome/")&&window.navigator.presentation?sya():window.chrome&&window.navigator.presentation&&!b7("Edge")?(c7(),Z6(Aza.map(pya))):$6())):i8("Cannot initialize because not running Chrome")},zza=function(){i8("dispose");
var a=m8();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);Cza(!1);g.lF(n8);n8.length=0},o8=function(){return!!g.cG("yt-remote-cast-installed")},Dza=function(){var a=g.cG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Eza=function(){i8("clearCurrentReceiver");
g.dG("yt-remote-cast-receiver")},Fza=function(){return o8()?m8()?m8().getCastSession():(k8("getCastSelector: Cast is not initialized."),null):(k8("getCastSelector: Cast API is not installed!"),null)},q8=function(){o8()?m8()?p8()?(i8("Requesting cast selector."),m8().requestSession()):(i8("Wait for cast API to be ready to request the session."),n8.push(g.kF("yt-remote-cast2-api-ready",q8))):k8("requestCastSelector: Cast is not initialized."):k8("requestCastSelector: Cast API is not installed!")},r8=
function(a,b){p8()?m8().setConnectedScreenStatus(a,b):k8("setConnectedScreenStatus called before ready.")},wza=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.UI||a},Gza=function(a,b){m8().init(a,b)},xza=function(a,b,c,d){var e=!1;
m8()||(a=new e8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.bG("yt-remote-cast-available",a);g.oF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i8("onReceiverSelected: "+a.friendlyName);
g.bG("yt-remote-cast-receiver",a);g.oF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i8("onReceiverResumed: "+a.friendlyName);
g.bG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i8("onSessionChange: "+N6(a));
a||g.dG("yt-remote-cast-receiver");g.oF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
i8("cloudview.createSingleton_: "+e);return e},m8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},yza=function(a,b){l8(!0);
j8(!1);Gza(a,function(a){a?(Cza(!0),g.nF("yt-remote-cast2-api-ready")):(k8("Failed to initialize cast API."),l8(!1),g.dG("yt-remote-cast-available"),g.dG("yt-remote-cast-receiver"),zza());b(a)})},i8=function(a){K7("cloudview",a)},k8=function(a){K7("cloudview",a)},l8=function(a){i8("setCastInstalled_ "+a);
g.bG("yt-remote-cast-installed",a)},p8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Cza=function(a){i8("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},j8=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},s8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Kf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},t8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Kf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.H)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},u8=function(a){return a.ob()?((0,g.H)()-a.D)/1E3:0},v8=function(a,b){a.F=b;
a.D=(0,g.H)()},w8=function(a){switch(a.g){case 1:case 1081:return((0,g.H)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},x8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&t8(a)},y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.l);b.hasPrevious=a.Kf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},A8=function(a,b){g.$E.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.MB;this.o=this.l=null;this.H=(0,g.z)(this.cO,this);this.D=(0,g.z)(this.zl,this);this.F=(0,g.z)(this.bO,this);this.I=(0,g.z)(this.pO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ku,this),Hza(this))):c=3;0!=c&&(b?this.Ku(c):g.qD((0,g.z)(function(){this.Ku(c)},this),0));
var d=Fza();d&&z8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},B8=function(a){return new s8(a.A.getPlayerContextData())},Hza=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.AQ,a),this))},a)},Iza=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C8=function(a,b){50>a.B.Ic()&&g.OB(a.B,b)},E8=function(a,b,c){var d=B8(a);
v8(d,c);-1E3!=d.g&&(d.g=b);D8(a,d)},F8=function(a,b,c){a.A.sendMessage(b,c)},D8=function(a,b){Iza(a);
a.A.setPlayerContextData(y8(b));Hza(a)},z8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.zl(null));
a.o=b;a.o&&(K7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.zl(a.o.media[0]))},Jza=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=B8(a);b.contentId!=d.videoId&&K7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;v8(d,a.l.getEstimatedTime());D8(a,d)}else K7("CP","No cast media video. Ignoring state update.")},G8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),F8(this,b,c))},a)},H8=function(a,b,c){g.$E.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.V=[];this.A=this.D=this.o=this.bb=this.g=null;this.ma=a;this.V.push(g.KE(window,"beforeunload",(0,g.z)(this.zH,this)));this.l=[];this.bb=new s8;this.X=b.id;this.g=Kza(this,c);this.g.subscribe("handlerOpened",this.gO,this);this.g.subscribe("handlerClosed",this.dO,this);this.g.subscribe("handlerError",this.eO,this);this.g.subscribe("handlerMessage",this.fO,this);Xya(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.hG()&&g.bG("yt-remote-session-video-id",a)},this)},I8=function(a){K7("conn",a)},Kza=function(a,b){return new E7(H7(a.ma,"/bc"),b)},J8=function(a,b){a.P("proxyStateChange",b)},Lza=function(a){a.B=g.qD((0,g.z)(function(){I8("Connecting timeout");
this.C(1)},a),2E4)},K8=function(a){g.sD(a.B);
a.B=window.NaN},L8=function(a){g.sD(a.M);
a.M=window.NaN},Mza=function(a){M8(a);
a.K=g.qD((0,g.z)(function(){N8(this,"getNowPlaying")},a),2E4)},M8=function(a){g.sD(a.K);
a.K=window.NaN},Oza=function(a,b){b&&(K8(a),L8(a));
b==(F7(a.g)&&(0,window.isNaN)(a.B))?b&&(J8(a,1),N8(a,"getSubtitlesTrack")):b?(a.W()&&a.bb.reset(),J8(a,1),N8(a,"getNowPlaying"),Nza(a)):a.C(1)},Pza=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Ub(b.params)?a.bb.l=null:a.bb.l=b.params,a.P("remotePlayerChange"))},Qza=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;x8(a.bb,c,d);a.P("remoteQueueChange")},Sza=function(a,b){b.params=b.params||{};
Qza(a,b);Rza(a,b);a.P("autoplayDismissed")},Rza=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
v8(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.H=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.bb.g?Mza(a):M8(a);
a.P("remotePlayerChange")},Tza=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);v8(a.bb,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},Uza=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.P("remotePlayerChange")},Vza=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Wza=function(a,b){var c="true"==b.params.hasNext;
a.bb.Kf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.P("previousNextChange")},Nza=function(a){g.sD(a.I);
a.I=g.qD((0,g.z)(a.C,a,1),864E5)},N8=function(a,b,c){c?I8("Sending: action="+b+", params="+g.tg(c)):I8("Sending: action="+b);
a.g.sendMessage(b,c)},O8=function(a){O7.call(this,"ScreenServiceProxy");
this.Xc=a;this.l=[];this.l.push(this.Xc.$_s("screenChange",(0,g.z)(this.aU,this)));this.l.push(this.Xc.$_s("onlineScreenChange",(0,g.z)(this.bQ,this)))},aAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.kD("MDX_CONFIG")||b;g.$F&&Sxa();V6();P8||(P8=new G7(b?b.loungeApiHost:void 0),jya()&&(P8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",Q8,void 0));Xza();var c=R8();if(!c){var d=new X7(P8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=R8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Bza(a,d,function(a){a?S8()&&r8(S8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.oF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),T8("Initializing: "+g.tg(b)),U8.push(g.kF("yt-remote-cast2-availability-change",function(){g.oF("yt-remote-receiver-availability-change")})),U8.push(g.kF("yt-remote-cast2-receiver-selected",function(){V8(null);
g.oF("yt-remote-auto-connect","cast-selector-receiver")})),U8.push(g.kF("yt-remote-cast2-receiver-resumed",function(){g.oF("yt-remote-receiver-resumed","cast-selector-receiver")})),U8.push(g.kF("yt-remote-cast2-session-change",Yza)),U8.push(g.kF("yt-remote-connection-change",function(a){a?r8(S8(),"YouTube TV"):W8()||(r8(null,null),Eza())})),a=X8(),b.isAuto&&(a.id+="#dial"),g.aE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T8(" -- with channel params: "+
g.tg(a)),Zza(a),c.start(),S8()||$za())},cAa=function(){var a=bAa();
o8()&&g.cG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},bAa=function(){var a=R8().Xc.$_gos();
var b=Y8();b&&Z8()&&(Q6(a,b)||a.push(b));return bya(a)},$8=function(){var a=dAa();
!a&&o8()&&Dza()&&(a={key:"cast-selector-receiver",name:Dza()});return a},dAa=function(){var a=bAa(),b=Y8();
b||(b=W8());return g.La(a,function(a){return b&&M6(b,a.key)?!0:!1})},Y8=function(){var a=S8();
if(!a)return null;var b=R8().je();return R6(b,a)},Yza=function(a){T8("remote.onCastSessionChange_: "+N6(a));
if(a){var b=Y8();b&&b.id==a.id?r8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){p8()?m8().stopSession():k8("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},T8=function(a){K7("remote",a)},R8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new O8(a):null}return e9},S8=function(){return g.x("yt.mdx.remote.currentScreenId_")},eAa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},fAa=function(){return g.x("yt.mdx.remote.connectData_")},V8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
V8(null);a||eAa("");g.wa("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.C)(Q8,function(b){b(a)}),Q8.length=0);
b&&!a?g.oF("yt-remote-connection-change",!1):!b&&a&&g.oF("yt-remote-connection-change",!0)},W8=function(){var a=g.hG();
if(!a)return null;var b=R8().je();return R6(b,a)},b9=function(a,b){Y8()&&Y8();
eAa(a.id);var c=new H8(P8,a,X8());c.connect(b,fAa());c.subscribe("beforeDisconnect",function(a){g.oF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)},$za=function(){var a=W8();
a?(T8("Resume connection to: "+N6(a)),b9(a,0)):(W6(),Eza(),T8("Skipping connecting because no session screen found."))},Xza=function(){var a=X8();
if(g.Ub(a)){a=U6();var b=g.cG("yt-remote-session-name")||"",c=g.cG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},X8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Zza=function(a){a?(g.bG("yt-remote-session-app",a.app),g.bG("yt-remote-session-name",a.name)):(g.dG("yt-remote-session-app"),g.dG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.XE(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.uP);this.o.O(b,"captionschanged",this.aO);this.o.O(b,"captionssettingschanged",this.yC);this.o.O(b,"videoplayerreset",this.zo);this.o.O(b,"mdxautoplaycancel",this.HG);this.V=this.o.O(b,"onVolumeChange",this.QA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.dB,this);c.subscribe("remotePlayerChange",this.Bl,this);c.subscribe("remoteQueueChange",this.zo,this);c.subscribe("autoplayUpNext",this.zA,
this);c.subscribe("previousNextChange",this.aB,this);c.subscribe("nowAutoplaying",this.SA,this);c.subscribe("autoplayDismissed",this.yA,this);this.suggestion=null;this.H=new g.WN(64);this.A=new g.Pt(this.uC,500,this);g.N(this,this.A);this.B=new g.Pt(this.vC,1E3,this);g.N(this,this.B);this.K=new d7(this.AT,0,this);g.N(this,this.K);this.C={};this.M=new g.Pt(this.ZC,1E3,this);g.N(this,this.M);this.I=new g.Nk(this.WK,1E3,this);g.N(this,this.I);this.N=g.y;this.yC();this.zo();this.Bl()},g9=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},gAa=function(a){g9(a,0);
a.A.stop();h9(a,new g.WN(64))},j9=function(a,b){if(i9(a)&&!a.D){var c=null;
b&&(c={style:a.l.xi()},g.bc(c,b));a.g.lC(a.l.ea(1).videoId,c);a.C=B8(a.g).l}},k9=function(a,b){var c=a.l.Xf();
if(c){var d=c.ge();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.wj;var m=B8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};x8(m,k,l);g.t(b)&&(v8(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);F8(c,"setPlaylist",q);e||D8(c,m);h9(a,new g.WN(1))},hAa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{iy:1});
c&&c.length?(a.l.Hd("captions","track",b),a.D=!1):(a.l.ql("captions"),a.D=!0)}else a.l.Hd("captions","track",{})},i9=function(a){return B8(a.g).videoId==a.l.ea(1).videoId},h9=function(a,b){a.B.stop();
var c=a.H;if(!g.cO(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.MT(a.l,d);a.H=b;iAa(a.F,c,b)}},l9=function(a){g.X.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.HU()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.dV(this,250);g.N(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);jAa(this,g.JT(a))},jAa=function(a,b){if(3==a.o.Qa()){var c={RECEIVER_NAME:a.o.xc("remote","currentReceiver").name};
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.ob()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},m9=function(a,b){g.t_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},n9=function(a){g.kU.call(this,a);
g.jG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:P6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.WN(64);this.H=0;if(!g.DL(g.W(this.g))){a=
this.g;var b=g.CT(a).H;b&&(b=b.o&&b.o.g)&&(b=new m9(a,b),g.N(this,b));b=new l9(a);g.N(this,b);g.eU(a,b.element,4)}},iAa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.iO(c,b))},o9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)a9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.dc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.wj,index:Math.max(a.g.yz(),0),currentTime:0==f?void 0:f}}else c=null;T8("Connecting to: "+g.tg(b));"cast-selector-receiver"==b.key?(V8(c||null),p8()?m8().setLaunchParams(c||null):k8("setLaunchParams called before ready.")):!c&&
d9()&&S8()==b.key?g.oF("yt-remote-connection-change",!0):(a9(),V8(c||null),c=R8().je(),(c=R6(c,b.key))&&b9(c,1))}},yya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},n7={"'":"\\'"},kAa={},Yxa={pV:"atp",I_:"ska",YZ:"que",jZ:"mus",E_:"sus"};
K6.prototype.Zm=function(){var a=new K6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var X6,T6="",a7=Y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",qya=Y6("loadCastFramework")||Y6("loadCastApplicationFramework"),Aza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(d7,g.M);g.h=d7.prototype;g.h.vH=function(a){this.A=arguments;this.g=!1;this.ua?this.o=(0,g.H)()+this.qc:this.ua=g.ng(this.B,this.qc)};
g.h.stop=function(){this.ua&&(g.og(this.ua),this.ua=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();d7.Z.U.call(this)};
g.h.wH=function(){this.o?(this.ua=g.ng(this.B,this.o-(0,g.H)()),this.o=null):(this.ua=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};e7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
e7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=f7.prototype;g.h.fi=null;g.h.vf=!1;g.h.jk=null;g.h.Eu=null;g.h.Pj=null;g.h.mj=null;g.h.jh=null;g.h.Ch=null;g.h.Fi=null;g.h.Lc=null;g.h.Ol=0;g.h.wf=null;g.h.qp=null;g.h.kh=null;g.h.Pk=-1;g.h.UB=!0;g.h.Qh=!1;g.h.Uq=0;g.h.Ho=null;var wya={},i7={};g.h=f7.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.sS=function(a){a=a.target;var b=this.Ho;b&&3==g.Qw(a)?b.kj():this.fD(a)};
g.h.fD=function(a){try{if(a==this.Lc)a:{var b=g.Qw(this.Lc),c=this.Lc.l,d=this.Lc.getStatus();if(g.sd&&!g.oc(10)||g.ud&&!g.nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ye&&!g.Uw(this.Lc))break a;this.Qh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));p7(this);var e=this.Lc.getStatus();this.Pk=e;var f=g.Uw(this.Lc);(this.vf=200==e)?(4==b&&l7(this),this.C?(xya(this,b,f),g.Ye&&this.vf&&3==b&&(this.A.R(this.l,"tick",this.lS),this.l.start())):k7(this,f),this.vf&&!this.Qh&&(4==b?this.g.xo(this):
(this.vf=!1,h7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kh=3,j7(13)):(this.kh=0,j7(14)),l7(this),m7(this))}}catch(k){this.Lc&&g.Uw(this.Lc)}finally{}};
g.h.lS=function(){var a=g.Qw(this.Lc),b=g.Uw(this.Lc);this.Ol<b.length&&(p7(this),xya(this,a,b),this.vf&&4!=a&&h7(this))};
g.h.wR=function(a){o7((0,g.z)(this.vR,this,a),0)};
g.h.vR=function(a){this.Qh||(p7(this),k7(this,a),h7(this))};
g.h.lB=function(a){o7((0,g.z)(this.uR,this,a),0)};
g.h.uR=function(a){this.Qh||(l7(this),this.vf=a,this.g.xo(this),this.g.rf(4))};
g.h.cancel=function(){this.Qh=!0;l7(this)};
g.h.OR=function(){this.jk=null;var a=(0,g.H)();0<=a-this.Eu?(2!=this.mj&&this.g.rf(3),l7(this),this.kh=2,j7(18),m7(this)):Aya(this,this.Eu-a)};g.h=Dya.prototype;g.h.Rq=null;g.h.re=null;g.h.Io=!1;g.h.yx=null;g.h.pn=null;g.h.Sq=null;g.h.Tq=null;g.h.Ke=null;g.h.yg=-1;g.h.Ok=null;g.h.pk=null;g.h.connect=function(a){this.Tq=a;a=r7(this.g,null,this.Tq);j7(3);this.yx=(0,g.H)();var b=this.g.F;null!=b?(this.Ok=b[0],(this.pk=b[1])?(this.Ke=1,Eya(this)):(this.Ke=2,t7(this))):(J6(a,"MODE","init"),this.re=new f7(this,void 0,void 0,void 0),this.re.fi=this.Rq,g7(this.re,a,!1,null,!0),this.Ke=0)};
g.h.IG=function(a){if(a)this.Ke=2,t7(this);else{j7(4);var b=this.g;b.gf=b.Yg.yg;A7(b,9)}a&&this.rf(2)};
g.h.pq=function(a){return this.g.pq(a)};
g.h.abort=function(){this.re&&(this.re.cancel(),this.re=null);this.yg=-1};
g.h.xx=function(){return!1};
g.h.eB=function(a,b){this.yg=a.Pk;if(0==this.Ke)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.gf=this.yg;A7(c,2);return}this.Ok=c[0];this.pk=c[1]}else c=this.g,c.gf=this.yg,A7(c,2);else if(2==this.Ke)if(this.Io)j7(7),this.Sq=(0,g.H)();else if("11111"==b){if(j7(6),this.Io=!0,this.pn=(0,g.H)(),c=this.pn-this.yx,!g.sd||g.oc(10)||500>c)this.yg=200,this.re.cancel(),j7(12),s7(this.g,this,!0)}else j7(8),this.pn=this.Sq=(0,g.H)(),this.Io=!1};
g.h.xo=function(){this.yg=this.re.Pk;if(this.re.vf)0==this.Ke?this.pk?(this.Ke=1,Eya(this)):(this.Ke=2,t7(this)):2==this.Ke&&((!g.sd||g.oc(10)?!this.Io:200>this.Sq-this.pn)?(j7(11),s7(this.g,this,!1)):(j7(12),s7(this.g,this,!0)));else{0==this.Ke?j7(9):2==this.Ke&&j7(10);var a=this.g;a.gf=this.yg;A7(a,2)}};
g.h.Il=function(){return this.g.Il()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=u7.prototype;g.h.Bk=null;g.h.Pd=null;g.h.kc=null;g.h.Qq=null;g.h.tn=null;g.h.Nv=null;g.h.In=null;g.h.xl=0;g.h.tN=0;g.h.kd=null;g.h.ah=null;g.h.qg=null;g.h.Uh=null;g.h.Yg=null;g.h.pp=null;g.h.yj=-1;g.h.vy=-1;g.h.gf=-1;g.h.ej=0;g.h.Vi=0;g.h.Sh=8;var B7=new g.xf;g.A(Gya,g.We);g.A(Hya,g.We);g.A(Iya,g.We);g.h=u7.prototype;g.h.connect=function(a,b,c,d,e){j7(0);this.Qq=b;this.Bk=c||{};d&&g.t(e)&&(this.Bk.OSID=d,this.Bk.OAID=e);this.C?(o7((0,g.z)(this.lw,this,a),100),Mya(this)):this.lw(a)};
g.h.lw=function(a){this.Yg=new Dya(this);this.Yg.Rq=null;this.Yg.l=this.B;this.Yg.connect(a)};
g.h.xx=function(){return 0==this.g};
g.h.jB=function(a){this.ah=null;Pya(this,a)};
g.h.iB=function(){this.qg=null;this.kc=new f7(this,this.o,"rpc",this.D);this.kc.fi=null;this.kc.Uq=0;var a=this.Nv.clone();g.zm(a,"RID","rpc");g.zm(a,"SID",this.o);g.zm(a,"CI",this.pp?"0":"1");g.zm(a,"AID",this.yj);v7(this,a);if(!g.sd||g.oc(10))g.zm(a,"TYPE","xmlhttp"),g7(this.kc,a,!0,this.In,!1);else{g.zm(a,"TYPE","html");var b=this.kc,c=!!this.In;b.mj=3;b.jh=I6(a.clone());zya(b,c)}};
g.h.eB=function(a,b){if(0!=this.g&&(this.kc==a||this.Pd==a))if(this.gf=a.Pk,this.Pd==a&&3==this.g)if(7<this.Sh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.qg){if(this.kc)if(this.kc.Pj+3E3<this.Pd.Pj)x7(this),this.kc.cancel(),this.kc=null;else break a;z7(this);j7(19)}}else this.vy=c[1],0<this.vy-this.yj&&37500>c[2]&&this.pp&&0==this.Vi&&!this.Uh&&(this.Uh=o7((0,g.z)(this.VN,this),6E3));else A7(this,11)}else b!=kAa.tW.g&&A7(this,11);else if(this.kc==a&&
x7(this),!g.F(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.yj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.In=e[2],e=e[3],null!=e?this.Sh=e:this.Sh=6,this.g=3,this.kd&&this.kd.Zv(),this.Nv=r7(this,this.Il()?this.In:null,this.Qq),Qya(this)):"stop"==e[0]&&A7(this,7):3==this.g&&("stop"==e[0]?A7(this,7):"noop"!=e[0]&&this.kd&&this.kd.Yv(e),this.Vi=0)}}};
g.h.VN=function(){null!=this.Uh&&(this.Uh=null,this.kc.cancel(),this.kc=null,z7(this),j7(20))};
g.h.xo=function(a){if(this.kc==a){x7(this);this.kc=null;var b=2}else if(this.Pd==a)this.Pd=null,b=1;else return;this.gf=a.Pk;if(0!=this.g)if(a.vf)1==b?(b=(0,g.H)()-a.Pj,B7.dispatchEvent(new Hya(B7,a.Fi?a.Fi.length:0,b,this.ej)),w7(this),this.A.length=0):Qya(this);else{var c=a.kh,d;if(!(d=3==c||7==c||0==c&&0<this.gf)){if(d=1==b)this.Pd||this.ah||1==this.g||2<=this.ej?d=!1:(this.ah=o7((0,g.z)(this.jB,this,a),Rya(this,this.ej)),this.ej++,d=!0);d=!(d||2==b&&z7(this))}if(d)switch(c){case 1:A7(this,5);
break;case 4:A7(this,10);break;case 3:A7(this,6);break;case 7:A7(this,12);break;default:A7(this,2)}}};
g.h.dH=function(a){if(!g.D(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.nT=function(a){a?j7(2):(j7(1),Sya(this,8))};
g.h.pq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Kw;a.F=!1;return a};
g.h.isActive=function(){return!!this.kd&&this.kd.isActive(this)};
g.h.rf=function(a){B7.dispatchEvent(new Iya(B7,a))};
g.h.Il=function(){return!(!g.sd||g.oc(10))};
g.h=Tya.prototype;g.h.Zv=function(){};
g.h.Yv=function(){};
g.h.Xv=function(){};
g.h.eq=function(){};
g.h.Xw=function(){return{}};
g.h.isActive=function(){return!0};g.A(D7,g.M);D7.prototype.o=function(){500<this.qc&&24E4>2*this.qc&&(this.qc*=2);this.A();this.l&&this.start()};
D7.prototype.start=function(){g.Qt(this.g,this.qc);this.l=(0,g.H)()+this.qc};
D7.prototype.stop=function(){this.g.stop();this.l=0};
D7.prototype.isActive=function(){return this.g.isActive()};g.A(E7,Tya);g.h=E7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Jd=function(a){return this.o.Jd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ue(this.o),Wya(this),g.Ue(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new u7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.kd=null);d.kd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.yj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):F7(this)&&Nya(this.g,c)};
g.h.Zv=function(){C7(this.l);this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)Nya(this.g,a[b])}this.P("handlerOpened")};
g.h.Xv=function(a){var b=2==a&&401==this.g.gf;if(4!=a&&!b){if(6==a||410==this.g.gf)b=this.l,b.g.stop(),b.qc=500;this.l.start()}this.P("handlerError",a)};
g.h.eq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Xw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.bc(a,this.B);return a};
g.h.Yv=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(C7(this.l),this.l.start(),Lya(this.g)):this.P("handlerMessage",new Uya(a[0],a[1]))};
g.h.UT=function(){this.l.isActive();var a=this.g,b=0;a.kc&&b++;a.Pd&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};G7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
G7.prototype.B=function(a){a(Error("request timed out"))};var dza=(0,g.H)(),J7=null,M7=Array(50),L7=-1,N7=!1;g.A(O7,g.$E);O7.prototype.je=function(){return this.g};
O7.prototype.contains=function(a){return!!Q6(this.g,a)};
O7.prototype.get=function(a){return a?R6(this.g,a):null};
O7.prototype.info=function(a){K7(this.D,a)};g.A(P7,g.$E);var lAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=P7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.ua)&&this.jD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.ua)||(g.sD(this.ua),this.ua=window.NaN)};
g.h.U=function(){this.stop();P7.Z.U.call(this)};
g.h.jD=function(){this.ua=window.NaN;this.g=g.GD(H7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.XT,this),onError:(0,g.z)(this.VT,this),nd:(0,g.z)(this.ZT,this)})};
g.h.XT=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new L6(c))};
g.h.VT=function(a){this.g=null;a.status&&404==a.status?this.l>=lAa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=lAa[this.l],this.ua=g.qD((0,g.z)(this.jD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.ZT=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(R7,O7);g.h=R7.prototype;g.h.start=function(){Q7(this)&&this.P("screenChange");!g.cG("yt-remote-lounge-token-expiration")&&hza(this);g.sD(this.l);this.l=g.qD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){Q7(this);eza(this,a);S7(this,!1);this.P("screenChange");b(a);a.token||hza(this)};
g.h.remove=function(a,b){var c=Q7(this);gza(this,a)&&(S7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.kp=function(a,b,c,d){var e=Q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.sD(this.l);R7.Z.U.call(this)};
g.h.IH=function(a){Q7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S7(this,!b);b&&K7(this.D,"Missed "+b+" lounge tokens.")};
g.h.HH=function(a){K7(this.D,"Requesting lounge tokens failed: "+a)};g.A(U7,g.$E);g.h=U7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.cG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?W7(this):(this.A=(0,g.H)()+3E5,g.bG("yt-remote-fast-check-period",this.A),this.Ot())};
g.h.isEmpty=function(){return g.Ub(this.g)};
g.h.update=function(){T7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.g,function(b,d){return b&&!!R6(a,d)},this);
V7(this,b)};
g.h.U=function(){g.sD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);U7.Z.U.call(this)};
g.h.Ot=function(){g.sD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=kza(this);if(g.Mb(a)){var b=H7(this.B,"/pairing/get_screen_availability");this.l=I7(this.B,b,{lounge_token:g.Ob(a).join(",")},(0,g.z)(this.XQ,this,a),(0,g.z)(this.WQ,this))}else V7(this,{}),W7(this)};
g.h.XQ=function(a,b){this.l=null;var c=g.Ob(kza(this));if(g.gb(c,g.Ob(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V7(this,d);W7(this)}else this.Zb("Changing Screen set during request."),this.Ot()};
g.h.WQ=function(a){this.Zb("Screen availability failed: "+a);this.l=null;W7(this)};
g.h.Zb=function(a){K7("OnlineScreenService",a)};g.A(X7,O7);g.h=X7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.kp=function(a,b,c,d){this.o.contains(a)?this.o.kp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K7(this.D,a),d(Error(a)))};
g.h.je=function(a){return a?this.g:g.Va(this.g,(0,g.Hd)(this.A,function(a){return!this.contains(a)},this))};
g.h.kD=function(){return(0,g.Hd)(this.je(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.lD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new P7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ue(f);d(Y7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ue(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.bU=function(a,b,c,d){g.GD(H7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new L6(d.screen||{});if(!e.name||oza(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);oza(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(Y7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
nd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Ue(this.o);g.Ue(this.l);X7.Z.U.call(this)};
g.h.YH=function(){pza(this);this.P("screenChange");this.l.update()};
X7.prototype.dispose=X7.prototype.dispose;g.A($7,g.$E);g.h=$7.prototype;g.h.yo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.pe=function(a){this.ha()||(a&&a8(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){K7(this.M,a)};
g.h.nD=function(){return null};
g.h.Wt=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){a8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Wt("");$7.Z.U.call(this)};g.A(b8,$7);g.h=b8.prototype;g.h.Vt=function(a){if(this.g){if(this.g==a)return;a8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);rza(this)};
g.h.zj=function(a){this.info("launchWithParams no-op for Cast: "+g.tg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.pe()},this),(0,g.z)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.Wt=g.y;g.h.U=function(){this.info("disposeInternal");g.sD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;b8.Z.U.call(this)};
g.h.YR=function(a,b){if(!this.ha())if(b){var c=g.Ew(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.tg(c));switch(d){case "mdxSessionStatus":qza(this,c.screenId);break;default:a8(this,"Unknown youtube message: "+d)}}else a8(this,"Unable to parse message.")}else a8(this,"No data in message.")};
g.h.mx=function(a,b,c,d){nza(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(a8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.qD((0,g.z)(this.mx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.nD=function(){return this.g};
g.h.cU=function(a){this.ha()||a||(a8(this,"Cast session died."),this.pe())};g.A(c8,$7);g.h=c8.prototype;g.h.Vt=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.zj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.sD(this.C);this.A?this.A.stop((0,g.z)(this.pe,this,null),(0,g.z)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.U=function(){this.g();this.g=g.y;g.sD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;c8.Z.U.call(this)};
g.h.fU=function(a){this.ha()||a||(a8(this,"DIAL session died."),this.g(),this.g=g.y,this.pe())};
g.h.Gr=function(a){this.I=P6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,tza(this));a(b);sza(this)}else this.D=(0,g.z)(function(){g.sD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,tza(this));a(b);sza(this)},this),this.C=g.qD((0,g.z)(function(){this.D()},this),100)};
g.h.pJ=function(a,b,c){nza(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.yo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Gr(b,c)},this),(0,g.z)(function(a){a8(this,"Failed to get DIAL screen: "+a);
this.Gr(b,c)},this))};g.A(d8,$7);d8.prototype.stop=function(){this.pe()};
d8.prototype.Vt=g.y;d8.prototype.zj=function(){g.sD(this.g);this.g=window.NaN;var a=R6(this.H.je(),this.l.label);a?this.yo(a):this.pe(Error("No such screen"))};
d8.prototype.U=function(){g.sD(this.g);this.g=window.NaN;d8.Z.U.call(this)};g.A(e8,g.$E);g.h=e8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.fB,this),(0,g.z)(this.IQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.GO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),aza(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.mD,this)),this.o=vza(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.tg(a))},this)),this.P("yt-remote-cast2-availability-change",g8(this)),b(!0))},this),(0,g.z)(function(a){this.Zb("Failed to initialize API: "+g.tg(a));
b(!1)},this))};
g.h.WS=function(a,b){f8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)f8("Unsetting old screen status: "+this.g.l.friendlyName),h8(this,null)}if(a&&b){if(!this.g){c=R6(this.l.je(),a);if(!c){f8("setConnectedScreenStatus: Unknown screen.");return}var d=uza(this,c);d||(f8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.tg(a))},this)));
f8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);h8(this,new d8(this.l,d),!0)}this.g.Wt(b)}else f8("setConnectedScreenStatus: no screen.")};
g.h.XS=function(a){this.ha()?this.Zb("Setting connection data on disposed cast v2"):this.g?this.g.zj(a):this.Zb("Setting connection data without a session")};
g.h.eU=function(){this.ha()?this.Zb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),h8(this,null)):f8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.fB,this),(0,g.z)(this.bR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.mD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ta(g.x("yt.mdx.remote.debug.handlers_")||[],Yya);g.Ue(this.g);e8.Z.U.call(this)};
g.h.Zb=function(a){K7("Controller",a)};
g.h.gB=function(a,b){this.g==a&&(b||h8(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.EQ=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),f8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)f8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{f8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:h8(this,
new d8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:h8(this,new c8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:h8(this,new b8(this.l,a));break;default:this.Zb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Zb("Stopping receiver w/o session: "+a.friendlyName)}else this.Zb("onReceiverAction_ called without receiver.")};
g.h.GO=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Zb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Zb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return f8("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Zb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);h8(this,new c8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.pJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Gr,b))};
g.h.fB=function(a){if(!this.ha()){f8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)f8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),h8(this,new b8(this.l,b),!0);else{this.Zb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=R6(this.l.je(),c.label);
d&&M6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(f8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ue(this.g),this.g=new b8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.gB,this,this.g)),this.g.zj(null));this.g.Vt(a)}}};
g.h.dU=function(){return this.g?this.g.nD():null};
g.h.bR=function(a){this.ha()||(this.Zb("Failed to estabilish a session: "+g.tg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&h8(this,null))};
g.h.IQ=function(a){f8("Receiver availability updated: "+a);if(!this.ha()){var b=g8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;g8(this)!=b&&this.P("yt-remote-cast2-availability-change",g8(this))}};
g.h.mD=function(){this.ha()||(this.o=vza(this),f8("Updating custom receivers: "+g.tg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.Zb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",g8(this)))};
e8.prototype.setLaunchParams=e8.prototype.XS;e8.prototype.setConnectedScreenStatus=e8.prototype.WS;e8.prototype.stopSession=e8.prototype.eU;e8.prototype.getCastSession=e8.prototype.dU;e8.prototype.requestSession=e8.prototype.requestSession;e8.prototype.init=e8.prototype.init;e8.prototype.dispose=e8.prototype.dispose;var n8=[];s8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";t8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Kf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
s8.prototype.ob=function(){return 1==this.g};
s8.prototype.getDuration=function(){return this.C?this.H+u8(this):this.H};
s8.prototype.clone=function(){return new s8(y8(this))};g.A(A8,g.$E);g.h=A8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,G8(this,"play")):F8(this,"play"),E8(this,1,w8(B8(this))),this.P("remotePlayerChange")):C8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,G8(this,"pause")):F8(this,"pause"),E8(this,2,w8(B8(this))),this.P("remotePlayerChange")):C8(this,this.pause)};
g.h.iD=function(a){if(1==this.g){if(this.l){var b=B8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ob()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,G8(this,"seekTo",{newTime:a}))}else F8(this,"seekTo",{newTime:a});E8(this,3,a);this.P("remotePlayerChange")}else C8(this,g.Fa(this.iD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,G8(this,"stopVideo")):F8(this,"stopVideo");var a=B8(this);a.index=-1;a.videoId="";t8(a);D8(this,a);this.P("remotePlayerChange")}else C8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=B8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){K7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){K7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F8(this,"setVolume",e)}c.muted=b;c.volume=a;D8(this,c)}else C8(this,g.Fa(this.setVolume,a,b))};
g.h.lC=function(a,b){if(1==this.g){var c=B8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.tg(b.style),g.bc(d,c.l));F8(this,"setSubtitlesTrack",d);D8(this,c)}else C8(this,g.Fa(this.lC,a,b))};
g.h.Ju=function(a,b){if(1==this.g){F8(this,"setAudioTrack",{videoId:a,audioTrackId:b.uc.id});var c=B8(this);c.audioTrackId=b.uc.id;D8(this,c)}else C8(this,g.Fa(this.Ju,a,b))};
g.h.hD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"previous")}else C8(this,g.Fa(this.hD,a,b))};
g.h.gD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"next")}else C8(this,g.Fa(this.gD,a,b))};
g.h.Dw=function(){1==this.g?F8(this,"dismissAutoplay"):C8(this,this.Dw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}A8.Z.dispose.call(this)};
g.h.U=function(){Iza(this);this.A=null;this.B.clear();z8(this,null);A8.Z.U.call(this)};
g.h.Ku=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.PB(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.AQ=function(a,b){this.P(a,b)};
g.h.cO=function(a){if(!a)this.zl(null),z8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=B8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D8(this,b)}};
g.h.zl=function(a){K7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),Jza(this),this.P("remotePlayerChange")};
g.h.bO=function(a){a?(Jza(this),this.P("remotePlayerChange")):this.zl(null)};
g.h.pO=function(){var a=Fza();a&&z8(this,a)};
g.h.Zb=function(a){K7("CP",a)};g.A(H8,g.$E);g.h=H8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;v8(this.bb,m);this.A="UNSUPPORTED";I8("Connecting with setPlaylist and params: "+g.tg(l));this.g.connect({method:"setPlaylist",params:g.tg(l)},a,eya())}else I8("Connecting without params"),
this.g.connect({},a,eya());Lza(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),J8(this,3));H8.Z.dispose.call(this)};
g.h.U=function(){K8(this);M8(this);L8(this);g.sD(this.H);this.H=window.NaN;g.sD(this.I);this.I=window.NaN;this.o=null;g.LE(this.V);this.V.length=0;this.g.dispose();H8.Z.U.call(this);this.A=this.D=this.l=this.bb=this.g=null};
g.h.zH=function(){this.C(2)};
g.h.gO=function(){I8("Channel opened");this.N&&(this.N=!1,L8(this),this.M=g.qD((0,g.z)(function(){I8("Timing out waiting for a screen.");this.C(1)},this),15E3));
iya(Vya(this.g),this.X)};
g.h.dO=function(){I8("Channel closed");(0,window.isNaN)(this.B)?W6(!0):W6();this.dispose()};
g.h.eO=function(a){W6();(0,window.isNaN)(this.F())?(I8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,I8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),J8(this,2))};
g.h.fO=function(a){a.params?I8("Received: action="+a.action+", params="+g.tg(a.params)):I8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Ew(a.params.devices);this.l=(0,g.I)(a,function(a){return new K6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Oza(this,a);break;case "loungeScreenDisconnected":g.Ua(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Oza(this,!1);break;case "remoteConnected":var b=new K6(g.Ew(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Ra(this.l,b);
break;case "remoteDisconnected":b=new K6(g.Ew(a.params.device));g.Ua(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Qza(this,a);break;case "nowPlaying":Sza(this,a);break;case "onStateChange":Rza(this,a);break;case "onAdStateChange":Tza(this,a);break;case "onVolumeChanged":Uza(this,a);break;case "onSubtitlesTrackChanged":Pza(this,a);break;case "nowAutoplaying":Vza(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Wza(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:I8("Unrecognized action: "+a.action)}};
g.h.ES=function(){if(this.o){var a=this.o;this.o=null;this.bb.videoId!=a&&N8(this,"getNowPlaying")}};
H8.prototype.subscribe=H8.prototype.subscribe;H8.prototype.unsubscribeByKey=H8.prototype.Jd;H8.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?F7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
H8.prototype.getProxyState=H8.prototype.da;H8.prototype.C=function(a){I8("Disconnecting with "+a);K8(this);this.P("beforeDisconnect",a);1==a&&W6();Wya(this.g,a);this.dispose()};
H8.prototype.disconnect=H8.prototype.C;H8.prototype.ca=function(){var a=this.bb;this.o&&(a=this.bb.clone(),x8(a,this.o,a.index));return y8(a)};
H8.prototype.getPlayerContextData=H8.prototype.ca;
H8.prototype.ka=function(a){var b=new s8(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.o=b.videoId,g.sD(this.H),this.H=g.qD((0,g.z)(this.ES,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&w8(this.bb)==w8(b)&&g.tg(this.bb.l)==g.tg(b.l)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
H8.prototype.setPlayerContextData=H8.prototype.ka;H8.prototype.W=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
H8.prototype.getOtherConnectedRemoteId=H8.prototype.W;H8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.H)():window.NaN};
H8.prototype.getReconnectTimeout=H8.prototype.F;H8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
H8.prototype.getAutoplayMode=H8.prototype.Y;H8.prototype.ba=function(){return this.D||""};
H8.prototype.getAutoplayVideoId=H8.prototype.ba;H8.prototype.na=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Rt(a.g);a.start()}};
H8.prototype.reconnect=H8.prototype.na;H8.prototype.fa=function(a,b){N8(this,a,b);Nza(this)};
H8.prototype.sendMessage=H8.prototype.fa;g.A(O8,O7);g.h=O8.prototype;g.h.je=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.kp=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.Xc.$_ubk(this.l[a]);this.l.length=0;this.Xc=null;O8.Z.U.call(this)};
g.h.aU=function(){this.P("screenChange")};
g.h.bQ=function(){this.P("onlineScreenChange")};
X7.prototype.$_st=X7.prototype.start;X7.prototype.$_gspc=X7.prototype.bU;X7.prototype.$_gsppc=X7.prototype.lD;X7.prototype.$_c=X7.prototype.contains;X7.prototype.$_g=X7.prototype.get;X7.prototype.$_a=X7.prototype.add;X7.prototype.$_un=X7.prototype.kp;X7.prototype.$_r=X7.prototype.remove;X7.prototype.$_gs=X7.prototype.je;X7.prototype.$_gos=X7.prototype.kD;X7.prototype.$_s=X7.prototype.subscribe;X7.prototype.$_ubk=X7.prototype.Jd;var P8=null,Q8=null,e9=null,U8=[];g.p(f9,g.M);g.h=f9.prototype;
g.h.U=function(){g.M.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.dB,this);this.g.unsubscribe("remotePlayerChange",this.Bl,this);this.g.unsubscribe("remoteQueueChange",this.zo,this);this.g.unsubscribe("autoplayUpNext",this.zA,this);this.g.unsubscribe("previousNextChange",this.aB,this);this.g.unsubscribe("nowAutoplaying",this.SA,this);this.g.unsubscribe("autoplayDismissed",this.yA,this);this.g=this.F=null};
g.h.kz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=B8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":B8(this.g).ob()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.kj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Ju(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Ju(this.l.ea(1).videoId,c)}};
g.h.aO=function(a){this.K.vH(a)};
g.h.AT=function(a){this.kz("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.yC=function(){var a=this.l.xc("captions","track");g.Ub(a)||j9(this,a)};
g.h.QA=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Bl,this);var b=Math.round(a.volume);a=!!a.muted;var c=B8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Bl,this)}};
g.h.uP=function(){g.Ub(this.C)||hAa(this,this.C);this.D=!1};
g.h.dB=function(a,b){this.B.stop();2==b&&this.vC()};
g.h.Bl=function(){if(i9(this)){this.A.stop();var a=B8(this.g);switch(a.g){case 1081:case 1:h9(this,new g.WN(8));this.uC();break;case 1085:case 3:h9(this,new g.WN(9));break;case 1083:case 0:h9(this,new g.WN(2));this.I.stop();g9(this,this.l.ea().lengthSeconds);break;case 1084:h9(this,new g.WN(4));break;case 2:h9(this,new g.WN(4));g9(this,w8(a));break;case -1:h9(this,new g.WN(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},h9(this,new g.WN(128,a))}a=B8(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,hAa(this,a));a=B8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.ZC()}else gAa(this)};
g.h.aB=function(){this.l.P("mdxpreviousnextchange")};
g.h.zo=function(){i9(this)||gAa(this)};
g.h.HG=function(){this.g.Dw()};
g.h.zA=function(a){a&&(a=g.GD("/watch_queue_ajax",{method:"GET",Tc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.zR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.zR=function(a,b){var c=new g.XM({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.SA=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.yA=function(){this.l.P("mdxautoplaycanceled")};
g.h.WK=function(a,b){-1==B8(this.g).g?k9(this,a):b&&this.g.iD(a)};
g.h.ZC=function(){if(i9(this)){var a=B8(this.g);this.o.Ca(this.V);a.muted?this.l.mute():this.l.Yf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.QA)}};
g.h.uC=function(){this.A.stop();if(!this.g.ha()){var a=B8(this.g);a.ob()&&h9(this,new g.WN(8));g9(this,w8(a));this.A.start()}};
g.h.vC=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(l9,g.X);l9.prototype.A=function(a){jAa(this,a.state)};g.p(m9,g.t_);m9.prototype.I=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.F=g.jb(a,this.B,this),g.u_(this,(0,g.I)(a,this.B)),a=this.l.xc("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.B=function(a){return a.key};
m9.prototype.pf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
m9.prototype.md=function(a){g.t_.prototype.md.call(this,a);this.l.Hd("remote","currentReceiver",this.F[a]);this.A.Nb()};g.p(n9,g.kU);g.h=n9.prototype;g.h.create=function(){aAa(g.sL(g.W(this.g)));this.C.push(g.kF("yt-remote-before-disconnect",this.WN,this));this.C.push(g.kF("yt-remote-connection-change",this.JQ,this));this.C.push(g.kF("yt-remote-receiver-availability-change",this.bB,this));this.C.push(g.kF("yt-remote-auto-connect",this.HQ,this));this.C.push(g.kF("yt-remote-receiver-resumed",this.GQ,this));this.bB()};
g.h.load=function(){this.g.Ks();g.kU.prototype.load.call(this);this.B=new f9(this,this.g,this.l);var a=(a=fAa())?a.currentTime:0;var b=d9()?new A8(Z8(),void 0):null;0==a&&b&&(a=w8(B8(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));iAa(this,this.D,this.D);g.D0(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Ve(this.B,this.l);this.l=this.B=null;g.kU.prototype.unload.call(this);g.D0(this.g.app,5)};
g.h.U=function(){g.lF(this.C);g.kU.prototype.U.call(this)};
g.h.jl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.kz.apply(this.B,[].concat([a],g.qa(c)))};
g.h.rH=function(){return this.loaded?this.B.suggestion:null};
g.h.Kf=function(){return this.l?B8(this.l).Kf:!1};
g.h.hasNext=function(){return this.l?B8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.xK=function(){var a=B8(this.l),b=this.g.ea();return{allowSeeking:this.g.Yc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+u8(a):a.A,isPeggedToLive:1>=(a.C?a.o+u8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+u8(a):a.o,seekableStart:0<a.B?a.B+u8(a):a.B}};
g.h.yK=function(){this.l&&this.l.gD()};
g.h.zK=function(){this.l&&this.l.hD()};
g.h.WN=function(a){1==a&&(this.I=this.l?B8(this.l):null)};
g.h.JQ=function(){var a=d9()?new A8(Z8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ue(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.wz(a.videoId,w8(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.bB=function(){this.F=[this.o].concat(cAa());var a=$8()||this.o;o9(this,a);this.g.pa("onMdxReceiversChange")};
g.h.HQ=function(){var a=$8();o9(this,a)};
g.h.GQ=function(){this.A=$8()};
g.h.wK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?q8():o9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&q8(),!0):!1}};
g.h.AK=function(){F8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.rd=function(){return!1};g.$_.remote=n9;})(_yt_player);
